
```{r setup}
#| include: false
# These colours match those in `themer.scss`
primary <- "#002145"
secondary <- "#6495ed"
tertiary <- "#a41623"
fourth_colour <- "#ffa319"
fifth_colour <- "#177245"
sixth_colour <- "#A393BF"
colvec <- c(
  primary = primary,
  secondary = secondary,
  tertiary = tertiary,
  fourth_colour = fourth_colour,
  fifth_colour = fifth_colour,
  sixth_colour = sixth_colour
)
theme_white <- "#fbfcff"
theme_black <- "#00162e"
my_url <- "https://dajmcdon.github.io"
paper_url <- "https://doi.org/10.1371/journal.pcbi.1012324"
slides_url <- "https://dajmcdon.github.io/rtestim-2025"
suppressMessages(library(tidyverse))
source("src/measles-bubble.R")
library(rtestim)
theme_set(
  theme_bw() +
    theme(
      plot.background = element_blank(),
      legend.background = element_blank(),
      legend.key = element_blank()
    )
)
delphi_pal <- function(n) {
  if (n > 6L) {
    warning("Not enough colors in this palette!")
  }
  unname(colvec)[1:n]
}
scale_fill_delphi <- function(..., aesthetics = "fill") {
  discrete_scale(aesthetics = aesthetics, palette = delphi_pal, ...)
}
scale_color_delphi <- function(..., aesthetics = "color") {
  discrete_scale(aesthetics = aesthetics, palette = delphi_pal, ...)
}
scale_colour_delphi <- scale_color_delphi
```

```{r, dev.args=list(bg=primary)}
#| include: false
#| label: cover-art
#| fig-width: 8
#| fig-height: 4.5
#| cache: true
rto <- estimate_rt(cancovid$incident_cases, x = cancovid$date)
Rt <- rto$Rt
colnames(Rt) <- as.character(1:ncol(Rt))
Rt <- pivot_longer(as_tibble(Rt) |> mutate(x = cancovid$date), -x) |>
  arrange(name, x)

Rt |>
  ggplot(aes(x, value, colour = as.numeric(name), group = name)) +
  geom_line() +
  coord_cartesian(
    ylim = c(0.8, 1.5),
    xlim = c(ymd("2021-08-01", "2022-08-31"))
  ) +
  scale_x_continuous(expand = expansion()) +
  scale_y_continuous(expand = expansion()) +
  theme_void() +
  scale_color_distiller(palette = "Set1", direction = 1) +
  theme(legend.position = "none")
```


```{r}
#| include: false
#| label: qrcodes
#| fig-width: 8
#| fig-height: 4
#| dev: "png"
#| cache: true
qrdat <- function(text, ecl = c("L", "M", "Q", "H")) {
  x <- qrcode::qr_code(text, ecl)
  n <- nrow(x)
  s <- seq_len(n)
  tib <- tidyr::expand_grid(x = s, y = rev(s))
  tib$z <- c(x)
  tib
}

allqr <- bind_rows(
  slides = qrdat(slides_url),
  paper = qrdat(paper_url),
  `my www` = qrdat(my_url, "Q"),
  `{rtestim}` = qrdat("https://dajmcdon.github.io/rtestim"),
  .id = "site"
) |>
  mutate(site = as.factor(site) |> fct_relevel("{rtestim}", after = 2))

ggplot(allqr, aes(x, y, fill = z, alpha = z)) +
  geom_raster() +
  coord_equal(expand = FALSE) +
  scale_fill_manual(values = c(theme_white, primary), guide = "none") +
  scale_alpha_manual(values = c(0, 1), guide = "none") +
  theme_void() +
  facet_wrap(~site, nrow = 1) +
  theme(
    text = element_text(color = primary, size = 36, margin = margin(3, 0, 3, 0))
  )
```

